apiVersion: v1
kind: Service
metadata:
  name: rundeck-service
  namespace: kuma
spec:
  selector:
    app: rundeck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4440
  type: NodePort
