apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: ci-cd
  ports:
    - port: 80        # Port exposed by the service
      targetPort: 8080  # Port the service forwards to inside the container
      nodePort: 31000    # NodePort that allows external access to Jenkins