apiVersion: v1
kind: Service
metadata:
  name: kuma-service
  namespace: kuma
spec:
  type: NodePort
  selector:
    app: kuma
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 31001
